version: '3'

services:
  redis-cluster-node-1:
    image: bitnami/redis-cluster:7.0
    environment:
      - REDIS_NODES=redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3
      - REDIS_PASSWORD=your_password
      - REDISCLI_AUTH=your_password
    ports:
      - "7001:6379"
    networks:
      - redis-cluster
    volumes:
      - node1-data:/bitnami

  redis-cluster-node-2:
    image: bitnami/redis-cluster:7.0
    environment:
      - REDIS_NODES=redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3
      - REDIS_PASSWORD=your_password
      - REDISCLI_AUTH=your_password
    ports:
      - "7002:6379"
    networks:
      - redis-cluster
    volumes:
      - node2-data:/bitnami

  redis-cluster-node-3:
    image: bitnami/redis-cluster:7.0
    environment:
      - REDIS_NODES=redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3
      - REDIS_PASSWORD=your_password
      - REDISCLI_AUTH=your_password
    ports:
      - "7003:6379"
    networks:
      - redis-cluster
    volumes:
      - node3-data:/bitnami

networks:
  redis-cluster:
    driver: bridge

volumes:
  node1-data:
  node2-data:
  node3-data:
