name: Proto Gen Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'proto/**'

env:
  GO_PROTO_REPO: github.com/streamweaverio/go-proto

jobs:
  generate_go_proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install protoc-gen-go
        run: |
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Generate Go Protos
        run: |
          make gen_go
          ls -la outputs/go