name: Proto Gen Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'proto/**'

env:
  OUTPUT_PATH: outputs
  GO_PROTO_REPO: github.com/streamweaverio/go-proto

jobs:
  generate_go_proto:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install protoc-gen-go
        run: |
          # Install protoc-gen-go and protoc-gen-go-grpc
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0
          
          # Ensure GOPATH/bin is in the PATH
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Generate Go Protos
        run: |
          make gen_go

      - name: Git Identity
        run: |
          git config --global user.name "Streamweaver Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch main

      - name: Git Setup
        env:
          OUTPUT_PATH: "${{ env.OUTPUT_PATH }}/go/${{ env.GO_PROTO_REPO }}"
        run: |
          cd $OUTPUT_PATH
          git init
          git remote add origin https://x-access-token:${{ secrets.WORKFLOW_GITHUB_PAT }}@${{ env.GO_PROTO_REPO }}

      - name: Commit Changes
        env:
          OUTPUT_PATH: "${{ env.OUTPUT_PATH }}/go/${{ env.GO_PROTO_REPO }}"
        run: |
          cd $OUTPUT_PATH
          git add .
          git commit -m "Update Go definitions"
          git push origin main

