name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pkg/**'
      - 'Dockerfile'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/pull-request.yaml'

jobs:
  integration:
    strategy:
      matrix:
        config:
          - job_name: Test
            go_version: 1.23
            cmd: |
              make test
          - job_name: Lint
            go_version: 1.23
            cmd: |
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
              make lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.config.go_version }}

      - name: Run ${{ matrix.config.job_name }}
        run: ${{ matrix.config.cmd }}